### ISSUE TITLE
Question of kernels on NVIDIA RTX 3090

### ISSUE THREAD

**Issue by guaniu22** [spcl/QuaRot#51]
**Describe the bug**
My environment is formed by Ubuntu 20.04, cuda 12.1.1, Nvidia RTX 3090 GPU, python3.10 and GCC version 11.4.0.
I got Assertion failed: Error Internal and RuntimeError: Error Internal while I tried `qlinear_benchmark.py`.
The output error is:
<pre><code>/home/chenzibo/QuaRot-main/quarot/functional/quantization.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  minq = torch.tensor(-maxq -1)
torch.float16. Sizes: torch.Size([4096, 4096])
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [5,0,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [6,0,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [0,8,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [14,8,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [18,8,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [29,8,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [30,8,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [25,4,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [1,6,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [5,6,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [19,6,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [22,6,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [30,6,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [24,1,0], thread: [24,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [24,1,0], thread: [26,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [5,9,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [12,9,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [20,9,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [30,9,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [0,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [15,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [54,1,0], thread: [31,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [50,1,0], thread: [1,11,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [50,1,0], thread: [20,11,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [50,1,0], thread: [28,11,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [23,5,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [27,5,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [42,1,0], thread: [0,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [42,1,0], thread: [2,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [42,1,0], thread: [11,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [42,1,0], thread: [13,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [42,1,0], thread: [23,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [8,0,0], thread: [2,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [8,0,0], thread: [5,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [8,0,0], thread: [15,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [8,0,0], thread: [17,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [8,0,0], thread: [26,12,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [0,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [5,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [16,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [29,14,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [8,10,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [26,1,0], thread: [26,10,0] Assertion `value < upper_bound` failed.
Assertion failed: Error Internal
Traceback (most recent call last):
  File "/home/chenzibo/QuaRot-main/benchmarks/qlinear_benchmark.py", line 142, in <module>
    linear4bit_benchmark(args)
  File "/home/chenzibo/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/chenzibo/QuaRot-main/benchmarks/qlinear_benchmark.py", line 94, in linear4bit_benchmark
    times_4bit.append(module_benchmark(int4_mod, x))
  File "/home/chenzibo/QuaRot-main/benchmarks/qlinear_benchmark.py", line 31, in module_benchmark
    out = module(x)
  File "/home/chenzibo/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenzibo/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenzibo/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/chenzibo/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenzibo/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenzibo/QuaRot-main/quarot/nn/linear.py", line 62, in forward
    x = matmul(x, self.weight)
  File "/home/chenzibo/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/chenzibo/QuaRot-main/quarot/nn/linear.py", line 35, in matmul
    return quarot._CUDA.matmul(A, B).view(*A_shape_excl_last, *B_shape_excl_last)
RuntimeError: Error Internal
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [7,6,0] Assertion `value < upper_bound` failed.
/home/chenzibo/QuaRot-main/third-party/cutlass/include/cutlass/integer_subbyte.h:96: cutlass::integer_subbyte<Bits, Signed>::integer_subbyte(int) [with int Bits = 4; __nv_bool Signed = true]: block: [6,0,0], thread: [27,6,0] Assertion `value < upper_bound` failed.

**Comment by guaniu22** [comment]
After recompiling cutlass by code `cmake .. -DCUTLASS_NVCC_ARCHS=90a`, this bug is solved.
